"""T2 v0: identity-search engine A/B -- does episodic memory + recombination
beat random search? (Intuition-Mechanism Program, registered prediction P5.)

Space: the polynomial ring generated by E2, E4, E6, Delta (exact integer
q-series to degree 24; Delta = eta^24 via pentagonal base^24). A PROPOSAL
asserts  c1*m1 + c2*m2 == 0  for two same-weight monomials m1,m2 (products
of <=3 basis elements) and signs c1,c2 in {+1,-1}. The verifier is exact
(coefficient-wise integer comparison) -- milliseconds.

TRUE relations are sparse: proportional monomial pairs such as
(E4^2, E8), (E4*E6, E10), (E4*E8, E4^3), (E2*E4^2, E2*E8), ...
The multiplicative structure gives recombination its power: from ANY hit,
multiplying both sides by any basis element yields another hit (when the
product stays within the monomial set) -- "已知成功模式 x 新元素".

Arms (equal proposal budget, same proposal space):
  A (random)  : uniform over weight-matched pairs, random signs
  B (memory)  : same, but (a) never retries a proposal, (b) after a hit,
                recombination proposals (m1*f, m2*f) get priority

Registered P5 (plan): B reaches first hit in <= 1/2 of A's time, and the
hit rate in the step right after a recombination event exceeds the A
baseline rate by 3x. Additional metrics: total hits, steps to 5th hit.

Run:  python t2_engine.py [--trials 20] [--budget 300]
"""
import argparse
import json
import random
import time
from itertools import combinations_with_replacement

import numpy as np

DEG = 24
BASIS_NAMES = ["E2", "E4", "E6", "Delta"]


# ---------- exact q-series (integer coefficients, degrees 0..DEG) ----------

def pentagonal_base():
    base = np.zeros(DEG + 1, dtype=np.int64)
    base[0] = 1
    k = 1
    while k * (3 * k - 1) // 2 <= DEG:
        for g in (k * (3 * k - 1) // 2, k * (3 * k + 1) // 2):
            if g <= DEG:
                base[g] += (-1) ** k
        k += 1
    return base


def eisenstein_exact(w):
    """E_w(q) to degree DEG with rational coefficients scaled to integers:
    E_w = 1 - (2w/B_w) * sum sigma_{w-1}(n) q^n.  Use the Bernoulli B_w
    exact rationals via fractions to stay exact."""
    from fractions import Fraction
    bern = {2: Fraction(1, 6), 4: Fraction(-1, 30), 6: Fraction(1, 42),
            8: Fraction(-1, 30), 10: Fraction(5, 66), 12: Fraction(-691, 2730),
            14: Fraction(7, 6), 16: Fraction(-3617, 510), 18: Fraction(43867, 798),
            20: Fraction(-174611, 330), 22: Fraction(854513, 138),
            24: Fraction(-236364091, 2730)}
    B = bern[w]
    c = Fraction(-2 * w, B)
    out = np.zeros(DEG + 1, dtype=np.object_)
    out[0] = Fraction(1)
    for n in range(1, DEG + 1):
        s = sum(d ** (w - 1) for d in range(1, n + 1) if n % d == 0)
        out[n] = c * s
    return out


def delta_exact():
    """Delta = q * Pi (1-q^n)^24 -- leading q^1 factor (was missing)."""
    base = pentagonal_base()
    d = base.copy()
    for _ in range(23):
        d = np.convolve(d, base)[: DEG + 1]
    out = np.zeros(DEG + 1, dtype=object)
    out[1:] = d[:DEG]
    return out


def mul(a, b):
    return np.convolve(a, b)[: DEG + 1]


def build_basis():
    e2 = eisenstein_exact(2)
    e4 = eisenstein_exact(4)
    e6 = eisenstein_exact(6)
    delta = delta_exact()
    # sanity: E4^3 - E6^2 must equal 1728*Delta exactly
    e4_3 = mul(mul(e4, e4), e4)
    e6_2 = mul(e6, e6)
    lhs = e4_3 - e6_2
    assert lhs[0] == 0 and np.array_equal(lhs[1:], 1728 * delta[1:]), \
        "ring sanity failed"
    return {"E2": e2, "E4": e4, "E6": e6, "Delta": delta}


def monomials(basis, max_factors=3, max_weight=24):
    """All products of <=3 basis elements with total weight <= 24."""
    items = [(n, s, {"E2": 2, "E4": 4, "E6": 6, "Delta": 24}[n])
             for n, s in basis.items()]
    monos = {}
    for name, s, w in items:
        monos[name] = (s, w, (name,))
    for _ in range(max_factors - 1):
        new = {}
        for name, (s, w, gens) in monos.items():
            for n2, s2, w2 in items:
                if w + w2 <= max_weight and len(gens) < max_factors:
                    key = name + "*" + n2
                    if key not in monos:
                        new[key] = (mul(s, s2), w + w2, gens + (n2,))
        monos.update(new)
    return {k: v for k, v in monos.items() if v[1] > 0}


def is_proportional(s1, s2):
    """Exact check: s1 == c*s2 for a rational c (integer ratio test)."""
    nz1 = np.nonzero(s1)[0]
    nz2 = np.nonzero(s2)[0]
    if len(nz1) != len(nz2) or not np.array_equal(nz1, nz2):
        return False
    if len(nz1) == 0:
        return False
    i = nz1[0]
    if s2[i] == 0:
        return False
    c = s1[i] / s2[i]
    if c != int(c):
        return False
    c = int(c)
    return np.array_equal(s1, c * s2)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--trials", type=int, default=20)
    ap.add_argument("--budget", type=int, default=300)
    args = ap.parse_args()

    basis = build_basis()
    monos = monomials(basis)
    by_weight = {}
    for name, (s, w, gens) in monos.items():
        by_weight.setdefault(w, []).append(name)
    n_mono = len(monos)
    print(f"basis {BASIS_NAMES}; monomials: {n_mono} "
          f"(weights {sorted(by_weight)})", flush=True)

    # ground-truth proportional pairs (for scoring; engine does not see this)
    truth = set()
    names = list(monos)
    for i in range(n_mono):
        for j in range(i + 1, n_mono):
            n1, n2 = names[i], names[j]
            if monos[n1][1] != monos[n2][1]:
                continue
            if is_proportional(monos[n1][0], monos[n2][0]):
                truth.add(frozenset((n1, n2)))
    print(f"ground-truth proportional pairs: {len(truth)} "
          f"of {n_mono*(n_mono-1)//2} same-weight pairs", flush=True)

    def verify(p):
        (n1, n2), (c1, c2) = p
        return is_proportional(monos[n1][0], monos[n2][0])

    def run_arm(memory: bool, seed: int):
        rng = random.Random(seed)
        seen, hits = set(), []
        recomb_events = recomb_hits = 0
        steps_first = None
        steps_to_hits = {}
        for step in range(1, args.budget + 1):
            if memory and hits:
                # recombination: multiply a known hit by a fresh basis element
                n1, n2 = rng.choice(hits)
                w = monos[n1][1]
                cands = [f for f in BASIS_NAMES
                         if monos[n1][1] + {"E2": 2, "E4": 4, "E6": 6,
                                            "Delta": 24}[f] <= 24]
                if cands:
                    f = rng.choice(cands)
                    m1, m2 = n1 + "*" + f, n2 + "*" + f
                    w2 = w + {"E2": 2, "E4": 4, "E6": 6, "Delta": 24}[f]
                    if (m1 in monos and m2 in monos
                            and frozenset((m1, m2)) not in seen):
                        recomb_events += 1
                        p = ((m1, m2), (1, -1))
                        seen.add(frozenset((m1, m2)))
                        if verify(p):
                            hits.append((m1, m2))
                            recomb_hits += 1
                            steps_to_hits.setdefault(len(hits), step)
                            if steps_first is None:
                                steps_first = step
                            continue
            # random fallback
            w = rng.choice([w for w in by_weight if len(by_weight[w]) > 1])
            n1, n2 = rng.sample(by_weight[w], 2)
            key = frozenset((n1, n2))
            if key in seen:
                continue
            seen.add(key)
            p = ((n1, n2), (1, -1))
            if verify(p):
                hits.append((n1, n2))
                steps_to_hits.setdefault(len(hits), step)
                if steps_first is None:
                    steps_first = step
        post_rate = recomb_hits / recomb_events if recomb_events else None
        return {"hits": len(hits), "steps_first": steps_first,
                "steps_5": steps_to_hits.get(5),
                "recomb_events": recomb_events,
                "recomb_hits": recomb_hits,
                "post_rate": post_rate}

    print(f"\n=== A/B ({args.trials} trials x budget {args.budget}) ===")
    summary = {}
    for arm, memory in (("A_random", False), ("B_memory", True)):
        runs = [run_arm(memory, seed=t) for t in range(args.trials)]
        agg = {}
        for k in runs[0]:
            vals = [r[k] for r in runs if r[k] is not None]
            agg[k] = round(float(np.mean(vals)), 2) if vals else None
            if k in ("steps_first", "steps_5") and len(vals) < len(runs):
                agg[k + "_misses"] = len(runs) - len(vals)
        summary[arm] = {"runs": runs, "mean": agg}
        print(f"  {arm:10s} mean: {agg}")

    a_rate = (summary["A_random"]["mean"]["hits"] / args.budget)
    b_post = summary["B_memory"]["mean"]["post_rate"]
    print(f"\n=== P5 reading ===")
    print(f"  baseline hit rate (A): {a_rate:.3f}")
    print(f"  B post-recombination hit rate: {b_post} "
          f"(registered: >= 3x baseline)")
    sf_a = summary["A_random"]["mean"]["steps_first"]
    sf_b = summary["B_memory"]["mean"]["steps_first"]
    print(f"  steps to first hit: A={sf_a} B={sf_b} (registered: B <= A/2)")

    with open("t2_results.json", "w", encoding="utf-8") as f:
        json.dump({"truth_pairs": len(truth), "summary": summary}, f, indent=1)
    print("results -> t2_results.json")


if __name__ == "__main__":
    main()
